version: "3.2"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: server
      POSTGRES_DB: grpc-server
      POSTGRES_PASSWORD: server
    ports:
      - 5656:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
